services:
  db:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/pgdata17/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.13.0
    labels:
      - traefik.enable=true
      - "traefik.http.routers.pgadmin.rule=Host(`db.emerson.abc.br`)"
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=le
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
  server:
    # build:
    # context: .
    # target: final
    image: financas-backend-image:latest
    # ports:
    # - 3001:8000
    environment:
      - PG_DBNAME=postgres
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - RUST_BACKTRACE=full
      - CLIENT_HOST=https://financas.emerson.abc.br
      - PG_USER=postgres
      - PG_PASSWORD=password
      - ADDRESS=0.0.0.0:8000
      - PORT=8000
      - AUTH0_AUDIENCE=https://financas-api.emerson.abc.br
      - AUTH0_DOMAIN=dev-bbmjk43j6ecm7qiu.us.auth0.com
      - RUST_LOG=debug
    labels:
      - traefik.enable=true
      - "traefik.http.routers.financas-api.rule=Host(`financas-api.emerson.abc.br`)"
      - traefik.http.routers.financas-api.service=financas-api
      - traefik.http.routers.financas-api.entrypoints=websecure
      - traefik.http.routers.financas-api.tls=true
      - traefik.http.routers.financas-api.tls.certresolver=le
      - traefik.http.services.financas-api.loadbalancer.server.port=8000
    depends_on:
      db:
        condition: service_healthy
