// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
use chrono::NaiveDateTime;
use bigdecimal::BigDecimal;
use uuid::Uuid;
#[derive(Queryable, Debug, Identifiable)]
pub struct Transaction {
    pub id: Uuid,
    pub transacted_date: NaiveDate,
    pub amount: BigDecimal,
    pub currency: String,
    pub account_id: Uuid,
    pub description: String,
    pub label: String,
    pub kind: String,
    pub opts: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(user_id))]
pub struct User {
    pub user_id: Uuid,
    pub identification: String,
    pub username: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(account_id))]
pub struct UsersAccount {
    pub account_id: Uuid,
    pub user_id: Uuid,
    pub identification: String,
    pub kind: String,
    pub initial_amount: BigDecimal,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

